services:
  - type: web
    name: scloudmusicbot2-0  # Исправьте имя на ваше
    env: node
    plan: free
    buildCommand: |
      npm install
      pip install --user yt-dlp spotdl
      export PATH="$PATH:$HOME/.local/bin"
    startCommand: PATH="$PATH:$HOME/.local/bin" node index.js
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: STORAGE_CHANNEL_ID
        sync: false
      - key: CHANNEL_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        value: "https://scloudmusicbot2-0.onrender.com"  # Ваш правильный URL
      - key: SESSION_SECRET
        sync: false
      - key: ADMIN_LOGIN
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false